CONTRIBUTING.rst

Clarifies repercussions to violating code of conduct
```release-note
NONE
```

Fix typo in code of conduct repercussions

---

setup.py

- Updates pypi package name to `gordon-dns` to avoid name conflict.
N/A
I looked at [namespace packages](https://packaging.python.org/guides/creating-and-discovering-plugins/), but it seemed like a fix for a problem we don't have yet, so I Kept It Simple. 
After this PR is reviewed and merged, I'll go ahead and register the name on pypi  and test-pypi via `python setup.py register`.
```release-note
NONE
```
cc @spotify/alf 
Update: it looks like travis will always fail for this PR like it does for the `master` and `develop` branches.

Change pypi pkg name to 'gordon-dns'

---

.coveragerc
docs-requirements.txt
docs/api.rst
docs/conf.py
gordon/__init__.py
gordon/interfaces.py
requirements.txt

It adds a collection of interfaces that define how a plugin and gordon interacts.
N/A
None
```release-note
NONE
```

Add core interfaces

---

CONTRIBUTING.rst

This PR clarifies the workflow around release branches.
N/A
N/A
```release-note
NONE
```
@econchick @spotify/alf

Clarify branching workflow

---

OWNERS
gordon/exceptions.py
gordon/interfaces.py
gordon/main.py

Fixes some typos and inconsistencies in formatting, also removes a NOQA that doesn't seem to be necessary anymore.
Fixes #
```release-note
```

fix some typos and inconsistencies in formatting

---

gordon/plugins_loader.py
tests/unit/test_plugins_loader.py

This PR changes the same functionality in the plugin_loader as does https://github.com/spotify/gordon-janitor/pull/10.
Thanks @descent3me and @smstone for pointing this out!
N/A
N/A
```release-note
NONE
```
@spotify/alf

Load config only for active plugins

---

docs/api.rst
gordon/interfaces.py

I pre-maturely merged #19 so this takes into account @descent3me 's observations & concerns and tries to abstract the API a bit further for easy/more natural handling.
N/A
```release-note
NONE
```
@spotify/alf

Improve abstraction of metrics interface API

---

README.rst
dev-requirements.txt
docs/Makefile

I've found [sphinx-autobuild](https://pypi.org/project/sphinx-autobuild/) quite handy for gordon-gcp and gordon-janitor. Might as well add it here!
N/A
```release-note
NONE
```

Add doc rendering/live reloading

---

CHANGELOG.rst
gordon/__init__.py

Prepare for the 0.0.1.dev3 release
Fixes #
@spotify/alf 
```release-note
```

Prepare v0.0.1.dev3 release

---

CHANGELOG.rst
gordon/__init__.py

Prepare for the `0.0.1.dev4` release:
* Add logging-based default metrics plugin.
* Emit basic metrics from core router.
* Add a basic graceful shutdown mechanism.
N/A
```release-note
```

Prepare dev release 0.0.1.dev4

---

gordon/main.py
gordon/plugins_loader.py
tests/unit/test_main.py
tests/unit/test_plugins_loader.py

I noticed this issue when trying to help get Gordon to run. Totally open to a better/more elegant way to do this.
Fixes #
FYI another release for this package will need to be made.
```release-note
Fix router setup.
```

Fix args for seting up router

---

CHANGELOG.rst
gordon/__init__.py

Prepare dev release 0.0.1.dev5
Fixes #
```release-note
```

Prepare dev release 0.0.1.dev5

---

gordon.toml.example
gordon/router.py

Improve the way we communicate with users.
Fixes #
@spotify/alf 
```release-note
```

Improve example and warning message

---

CHANGELOG.rst
gordon/__init__.py

As it says, preparing for dev release 0.0.1.dev6 😄 
Fixes #
```release-note
```

Prepare dev release 0.0.1.dev6

---

CHANGELOG.rst
gordon/__init__.py

🎉  🎁 
Fixes #
```release-note
```
@spotify/alf

Prepare dev release 0.0.1.dev7

---

docs/config.rst
gordon.toml.example

In testing this, I realized that the docs were incorrect in terms of what the actual config kwargs are for ulogger.
Fixes #
```release-note
```
@spotify/alf

Fix docs for ulogging config

---

gordon/metrics/ffwd.py

It's reasonable that context may be reused for multiple calls to metrics plugins, so we should not be mutating the object that comes in.
Fixes #
@spotify/alf 
```release-note
* Remove mutation of the context passed to ffwd plugin.
```

[ffwd] Don't mutate the context passed to metrics

---

CHANGELOG.rst
gordon/__init__.py

Bump version to 0.0.1.dev8, pick up most recent changes.
Fixes #
```release-note
```

Prepare 0.0.1.dev8 release

---

requirements.txt

See https://github.com/spotify/gordon/pull/48

Bump toml to fix build

---

MANIFEST.in
catalog-info.yaml

Add catalog-info
